# Permalinks
#
permalink:           /:year/:month/:day/:title/
# permalink: pretty

# Setup
title:               daniel.industries
tagline:             "seeking, stories, beauty, meaning"
url:                 http://daniel.industries
baseurl:             ""
exclude:             []

excerpt_separator: ""

# About/contact
author:
  name:              Daniel Miller
  url:               http://daniel.industries
  email:             dealingwith@gmail.com

plugins:
  - jekyll-postcss

collections:
  writings:
    output: true
