# Permalinks
# permalink: pretty
permalink: /:year/:month/:day/:title/

# Setup
title: "daniel.industries"
tagline: "seeking, stories, beauty, meaning"
url: "https://daniel.industries"
baseurl: ""
exclude:
  - "*.rb"
  - "Rakefile"
  - "*.csv"
  - "rsync-exclude"
  - "README.md"

highlighter: rouge

# About/contact
author:
  name: "Daniel Miller"
  url: "http://daniel.industries"
  email: "dealingwith@gmail.com"

plugins:
  - match_regex

collections:
  writings:
    output: true
