# Permalinks
#
permalink:           /:year/:month/:day/:title/
# permalink: pretty

# Setup
title:               "daniel.industries"
tagline:             "seeking, stories, beauty, meaning"
url:                 "https://daniel.industries"
baseurl:             ""
exclude:             []

highlighter:         rouge

# About/contact
author:
  name:              "Daniel Miller"
  url:               "http://daniel.industries"
  email:             "dealingwith@gmail.com"

plugins:
  - match_regex

collections:
  writings:
    output: true
